### ISSUE TITLE
feat: Supports styles and calls similar to contextmenu

### ISSUE THREAD

**Issue by drl990114** [amrbashir/menu-rs#102]
Currently, no such API has been found.

This may require supporting native contextmenus first, and then menus can be formatted as contextmenus.

This allows for customized display positions and eliminates the need to repeatedly define menus.

<img width="414" alt="image" src="https://github.com/tauri-apps/muda/assets/48054715/5d81a6d3-d989-4926-b873-d20de038a468">

**Comment by amrbashir** [comment]
Not sure what you mean exactly but have you looked at https://docs.rs/muda/latest/x86_64-pc-windows-msvc/muda/struct.Submenu.html#method.show_context_menu_for_hwnd and the similar method on linux and macOS?

**Comment by drl990114** [comment]
Thank you, I'm sorry I didn't see this before
