### ISSUE TITLE
[bug] Tauri crashes when clicking on menu item that belongs to replaced system tray menu

### ISSUE THREAD

**Issue by jorge-menjivar** [amrbashir/menu-rs#173]
# To Reproduce
Tested on macOS 14.3.1. Open the system tray menu and keep it open while the system menu gets updated in the background just as shown in #129. Click on the menu item of the still open menu. App will crash.

# Trace
[thread main panicked at.txt](https://github.com/tauri-apps/muda/files/14761122/thread.main.panicked.at.txt)

# Repo to Reproduce
https://github.com/jorge-menjivar/tauri-tray-bug

**Comment by amrbashir** [comment]
cc @pewsheen

**Comment by pewsheen** [comment]
I'll tend to close the menu when we drop it, but it will look a little weird.

**Comment by amrbashir** [comment]
I guess we should close it to avoid crashes, it will look weird because it is not recommended to recreate the whole menu and instead update its items.
