### ISSUE TITLE
show_context_menu_for_hwnd() requires self to last for the lifetime of the pop up

### ISSUE THREAD

**Issue by npwoods** [amrbashir/menu-rs#204]
`Menu::show_context_menu_for_hwnd()` takes `&self` and returns immediately.  If `&self` is dropped or moved, the act of selecting a menu item will result in a stray memory access.

Shouldn't this be changed to something safe (e.g. - taking `Rc<Menu>`) or be marked as `unsafe`?  Though I suspect that anybody using `muda` and messing around with `HWND`s is in any case "'going offroad'"

**Comment by amrbashir** [comment]
`Menu` itself is a wrapper around `Rc<Menu>`.

I am fine with marking the function as `unsafe` and adding more documentation around this.

**Comment by npwoods** [comment]
Related to this issue I've noticed freeze-ups that seemingly go away if when I prepare my popup menus, I ensure that any items that are passed to `Menu::with_items()` or `Submenu::with_items()` are passed to `Box::leak()` to guarantee that they live for the lifetime of the popup menu being live.

Overall this is not surprising, as `muda` seems to be a low level library (and I come from the C++ world ;-)).  I'd just like to understand what I as a caller need to do.

**Comment by npwoods** [comment]
A question - while a popup menu is active, the menu has to be kept around.  If a menu item is selected, I know the pop up menu has done its job and it can be dropped.  But as far as I can tell, there is no reliable way to gauge whether the pop up menu is done if the user clicked out of it.
