### ISSUE TITLE
`from_cargo_metadata` pulling from muda crate instead of binary

### ISSUE THREAD

**Issue by PrimmR** [amrbashir/menu-rs#207]
Whenever I use the `from_cargo_metadata` method of `AboutMetadata` I get the details of the muda crate instead of the binary the method is being called from, which I assume is not the intended behaviour.

This could be fixed by changing the `env!` macro to `std::env::var`, as the latter means the environment variable is checked at runtime, so they hold the details of the binary, not the muda crate.

**Comment by FabianLars** [comment]
`std::env::var` won't work outside of `cargo run` either. :/

**Comment by amrbashir** [comment]
I guess the only fix to this, is to convert it into a macro:
```rs
let metadata = about_metadata::from_cargo_metadata!();
```

**Comment by FabianLars** [comment]
tbh i wouldn't even mind removing it completely. The current impl is imo small enough to just be an example / something that devs can include in their own code 🤷
