### ISSUE TITLE
Keys are not being recognized

### ISSUE THREAD

**Issue by 0PandaDEV** [amrbashir/menu-rs#231]
```bash
Error registering shortcut: GlobalHotkey("Couldn't recognize \"ControlLeft\" as a valid key for hotkey, if you feel like it should be, please report this to https://github.com/tauri-apps/muda")
```

Im on a M1 Pro. In the [docs.rs](https://docs.rs/tauri-plugin-global-shortcut/2.0.0-rc.2/tauri_plugin_global_shortcut/enum.Code.html) it says that this key exists.

I have the same problem with all the modifier keys ControlLeft, ControlRight, MetaLeft, MetaRight, ShiftLeft, ShiftRight, AltLeft, AltRight.

**Comment by 0PandaDEV** [comment]
?

**Comment by amrbashir** [comment]
These keys are modifiers and can't be used as keys.
