### ISSUE TITLE
Need native i18n support

### ISSUE THREAD

**Issue by nyssance** [amrbashir/menu-rs#235]
Now it's just support English.

**Comment by amrbashir** [comment]
Each menu item supports creating with a custom text using either the [`new`](https://docs.rs/muda/latest/muda/struct.MenuItem.html#method.new) method, or the [`text`](https://docs.rs/muda/latest/muda/struct.MenuItemBuilder.html#method.text) method on the builder  variant. You can also set the text after creation using [`set_text`](https://docs.rs/muda/latest/muda/struct.MenuItem.html#method.set_text) method. 

All predefined menu items support taking an optional argument to set the text https://docs.rs/muda/latest/muda/struct.PredefinedMenuItem.html#method.minimize 

All of these methods should help you implement i18n in your app for menus.
