### ISSUE TITLE
Show images/icons in system tray menu items

### ISSUE THREAD

**Issue by fnune** [amrbashir/menu-rs#30]
This issue is cross-posted from https://github.com/tauri-apps/tao/issues/645

## Linux

GTK menu items can be passed a box as a child instead of labels:

```rust
let mut menu = gtk::Menu::new();
                                                                                             
// A bit of a hack: this defaults to `false` in most "modern" (2010+ or so) DEs. This line
// enables menu images just for this application.
let settings = gtk::Settings::default().unwrap();
glib::ObjectExt::set_property(&settings, "gtk-menu-images", true);
                                                                                             
// One used to be able to instantiate an ImageMenuItem, but now one needs to build a box and
// pack some children instead:
let image = gtk::Image::from_file(icon_path.join("icon.png"));
let label = gtk::Label::new(Some("Hi there"));
                                                                                             
let mut menu_item_box = gtk::Box::builder().build();
menu_item_box.pack_start(&image, true, true, 0);
menu_item_box.pack_start(&label, true, true, 0);
                                                                                             
let menu_item = gtk::builders::MenuItemBuilder::new().child(&menu_item_box).build();
menu.append(&menu_item);
                                                                                             
indicator.set_menu(&mut menu);
menu.show_all();
                                                                                             
gtk::main();
```

`ImageMenuItem` is deprecated: https://docs.gtk.org/gtk3/class.ImageMenuItem.html

## MacOS

Not sure how it would be implemented but going by MeetingBar, it's possible: https://github.com/leits/MeetingBar

**Comment by amrbashir** [comment]
without `gtk::ImageMenuItem`, there will be an ugly padding at the start, see the first one

![image](https://user-images.githubusercontent.com/48618675/209947143-4ea32404-d4a8-42bc-9b55-f352c0ea7213.png)

more at https://stackoverflow.com/questions/48452717/how-to-replace-the-deprecated-gtk3-gtkimagemenuitem

**Comment by fnune** [comment]
When I do this using GNOME 3.38 the image appears on the right and looks quite good!

![image](https://user-images.githubusercontent.com/16181067/209981271-d0e21646-880b-482d-9aa1-16fca88654f9.png)

**Comment by fnune** [comment]
But I haven't tried GTK4. Maybe that looks worse.

**Comment by amrbashir** [comment]
we are using GTK3, and it is weird that it is on the Right, it is supposed to be on the left, here is an example with my current implementation with the default `Adawita` theme
![image](https://user-images.githubusercontent.com/48618675/209982616-1a66a85c-c355-4583-a479-a9444ab2003f.png)

**Comment by fnune** [comment]
For what it's worth my box is Debian stable (11/bullseye). And:

```
 ~/.dotfiles [127] => gnome-shell --version                                                                                            17:47:27
GNOME Shell 3.38.6
```

**Comment by amrbashir** [comment]
found a workarouond! 
![image](https://user-images.githubusercontent.com/48618675/209984097-e9024203-fe5f-4783-8be8-1979cde2237c.png)

by adding a custom css to the menu item and using `margin-left: -22px;`:
```rs
        let box_container = gtk::Box::new(Orientation::Horizontal, 6);
        let style_context = box_container.style_context();
        let css_provider = gtk::CssProvider::new();
        let theme = r#"
            box {
                margin-left: -22px;
            }
          "#;
        let _ = css_provider.load_from_data(theme.as_bytes());
```

**Comment by fnune** [comment]
Looks good, but the pixel value probably won't work for all environments... I also wonder what makes my image appear on the right side :eyes:

**Comment by fnune** [comment]
I don't know how many CSS features are available. Maybe you can do a `transformX(-100%)` or something...? I'm still unsure a portable solution is attainable.

**Comment by amrbashir** [comment]
> Looks good, but the pixel value probably won't work for all environments... 

yeah, but it is a start, I will look into it again later if someone reports it.
