### ISSUE TITLE
Show context menu for any window

### ISSUE THREAD

**Issue by Eliot00** [amrbashir/menu-rs#41]
I want to show a context menu whatever current window is, like [this clipboard extension app](https://github.com/Clipy/Clipy).

Can muda use `WindowId` to show context menu?

```rust
            Event::WindowEvent {
                window_id,
                ..
            } => {
                    menu.show_context_menu_for_window_id(window_id, x, y);

            }
```

**Comment by amrbashir** [comment]
do you mean any window? one that is not necessarily created by your app?

**Comment by Eliot00** [comment]
> do you mean any window? one that is not necessarily created by your app?

yeah, such as firefox window

**Comment by amrbashir** [comment]
I am not sure if possible, but if you can get a reference to an [`NSWindow`](https://developer.apple.com/documentation/appkit/nswindow?language=objc) you can use it to get the [content view](https://developer.apple.com/documentation/appkit/nswindow/1419160-contentview?language=objc) and pass it to https://docs.rs/muda/latest/x86_64-apple-darwin/muda/trait.ContextMenu.html#tymethod.show_context_menu_for_nsview
