### ISSUE TITLE
what is the status of muda in relationship to tao/wry?

### ISSUE THREAD

**Issue by PerBothner** [amrbashir/menu-rs#43]
I'm a bit unclear on the Muda "roadmap".
* Is Muda considered "more-or-less done" or a "work-inprogress"?
* The Muda examples use platform-specific conditional code.  This seems awkard.
* What is the preferred menu package for Tao and Wry applications? The `example/menu.rs` in the Wry code uses a different package `tao::menu`.
* Is the plan that Muda will replace `tao:menu` or that the latter will be re-implemented on top of Muda? Having two menu packages seems bad.

**Comment by amrbashir** [comment]
The plan is to remove `menu`, `global_shortcut` and `system_tray` modules from tao and users will need to migrate to using the dedicated `muda`, `global-hotkey` and `tray-icon` crates.

There is a branch in tao repo where all of this is removed in https://github.com/tauri-apps/tao/tree/muda and you can find examples in each of these crates on how to integrate it into a tao/wry app.

**Comment by amrbashir** [comment]
> Is Muda considered "more-or-less done" or a "work-inprogress"?

it is considered done IMO.

> The Muda examples use platform-specific conditional code. This seems awkard.

Well, it is needed unfortunately.

**Comment by PerBothner** [comment]
Thanks for the update. I figure it makes sense for me to wait until the Muda branch becomes the default.
