### ISSUE TITLE
docs: Some `PredefinedMenuItem`s not showing on Linux

### ISSUE THREAD

**Issue by virtualritz** [amrbashir/menu-rs#50]
Specifically, I only use `PredefinedMenuItem::show_all` and `PredefinedMenuItem::quit`.

They do not show up in my menu at all on Linux.
If they're not supported there they should be excluded on that platform?

**Comment by amrbashir** [comment]
quit and show_all is not supported on Linux, I seem to have forgotten to add documentation for it, thanks for the report and I will try to update it ASAP.
