### ISSUE TITLE
Updating multiple menu items during one event seems to cause a panic (Windows)

### ISSUE THREAD

**Issue by 0x1mason** [amrbashir/menu-rs#57]
This is identical to https://github.com/tauri-apps/muda/issues/40, except that the issue is happening on Windows. Also, I was using the example in https://github.com/tauri-apps/tray-icon/blob/dev/examples/tao.rs. 

It looks like the original patch https://github.com/tauri-apps/muda/pull/48 was only applied for Linux.

```shell
TrayEvent { id: 1, x: 2305.0, y: 1278.0, icon_rect: Rectangle { left: 2281.0, right: 2321.0, top: 1255.0, bottom: 1295.0 }, event: Right }
TrayEvent { id: 1, x: 2304.0, y: 1271.0, icon_rect: Rectangle { left: 2281.0, right: 2321.0, top: 1255.0, bottom: 1295.0 }, event: Left }
TrayEvent { id: 1, x: 2304.0, y: 1271.0, icon_rect: Rectangle { left: 2281.0, right: 2321.0, top: 1255.0, bottom: 1295.0 }, event: Right }
thread 'main' panicked at 'already mutably borrowed: BorrowError', C:\Users\eric\.cargo\registry\src\github.com-1ecc6299db9ec823\muda-0.4.4\src\platform_impl\windows\mod.rs:445:26
```

**Comment by amrbashir** [comment]
Could you give a minimal repro example, I can't repro it at all.

**Comment by 0x1mason** [comment]
Windows 11

1.
```shell
git clone https://github.com/tauri-apps/tray-icon
cd tray-icon
cargo run --example tao
```

2. Right-click icon, then left-click `About`
3. Right-click icon, then left-click `Quit`
4. See
```shell
thread 'main' panicked at 'already mutably borrowed: BorrowError', C:\Users\eric\.cargo\registry\src\github.com-1ecc6299db9ec823\muda-0.4.4\src\platform_impl\windows\mod.rs:445:26
```

**Comment by 0x1mason** [comment]
I also get it when clicking `About` twice.

**Comment by amrbashir** [comment]
I see, it is an issue with the `About` menu item itself, when you click on `About`, it spawns a dialog which stays open and it won't return until the user closes it, and triggering another menu item will definitely panic since the previous win32 callback hasn't returned yet. PR is up #60

**Comment by 0x1mason** [comment]
@amrbashir My dependency is on `tray-icon`. Is there a way for me to get the fix without forking and updating myself?

**Comment by amrbashir** [comment]
Just run `cargo update -p muda`, a new version has been released.
